### PR TITLE
Fix example in Introduction

### PR DESCRIPTION
**Pull request by surma**

### CODE REVIEW

**Comment by yoavweiss** [comment]
Hey @surma, could you join the WICG to appease the IPR bots? :)

**Comment by surma** [comment]
Done!

**Comment by surma** [comment]
Marked as non-substantive for IPR from ash-nazg.

**Comment by surma** [comment]
Sorry for marking as it as non-substantive, I clicked that by accident and I don’t know how to revert.

**Comment by yoavweiss** [comment]
I don't know if you can revert with current UI... I'll open an issue

**Comment by surma** [comment]
For the time being, I’ll re-open.

**Pull request closed without merging**
