### PR TITLE
Fix typo in first example

### PR DESCRIPTION
**Pull request by eeeps**
Note that my first every attempt at Bikeshedding a thing seems to have made some other, possibly-extraneous changes?

### CODE REVIEW

**Comment by atotic** [comment]
Thanks for the fix. I'll enter this manually to avoid the whole approval prerequisites procedure. Also, you do not need to regenerate bikeshed file, I do it only after enough revisions accumulate.

**Comment by yoavweiss** [comment]
@atotic - Please don't bypass the IPR bots by landing things manually. If you consider a change non-substantive (as this one probably is) you could mark it as such or ask one of the chair to do that for you.

**Comment by atotic** [comment]
Sure. I am not familiar with the proper procedures. Are they written anywhere?
- who can make pull requests?
- what's the approval procedure?

**Comment by yoavweiss** [comment]
We really need to properly document this, but in the mean time:
- WICG members can make pull requests to WICG repos. Non-members need to sign up to the WICG if their contributions are substantive (for IPR reasons).
- For non-substantive contributions (e.g. typos), you can client on the "details" link next to IPR bot failures in the PR page and get to a page like [this](https://labs.w3.org/hatchery/repo-manager/pr/id/WICG/ResizeObserver/26) where you can mark the PR as non-substantive.
- If that's not the case, you need to ask the contributor to join the WICG.

I usually try to handle the above for repo maintainers. In this particular case, my inbox made sure that the IPR failure will get lost in a sea of pending code reviews and issues :/

**Comment by atotic** [comment]
> "get to a page like this where you can mark the PR as non-substantive."

This is where I got stuck. Page looked suspicious, and I did not want to login into something I did not know.

**Comment by yoavweiss** [comment]
If you prefer that I'd take care of these issues in the future, feel free to ping me (here, and if that doesn't help, IRC/twitter)

**Comment by eeeps** [comment]
As long as we're talking process...
1. For big stuff, I gather that good etiquette is to submit an Issue, and then if there’s consensus of some kind, a PR. For smaller or “non-substatial” stuff, is it better to submit a PR, Issue, or both?
2. I'm a member [here](https://www.w3.org/community/wicg/participants), does that qualify me to submit PRs to WICG repos? Or do I need membership within GitHub somewhere?

**Comment by yoavweiss** [comment]
1. That's up to the repo, IMO.
2. I'll add you to the system then (you were supposed to be added automatically, but _shrug_)

**Pull request closed without merging**
